# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EOFS.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#5-12-21 Added .connect to each object name -erika
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import *


class Ui_Form(object):

    currentMood = ""
    currentReason = ""

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 476)
        self.HappyButton = QtWidgets.QPushButton(Form)
        self.HappyButton.setGeometry(QtCore.QRect(30, 80, 75, 23))
        self.HappyButton.click.connect(self.HappyButton)
        self.HappyButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.HappyButton.setObjectName("HappyButton")
        self.SadButton = QtWidgets.QPushButton(Form)
        self.SadButton.setGeometry(QtCore.QRect(100, 80, 75, 23))
        self.SadButton.click.connect(self.SadButton)
        self.SadButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.SadButton.setObjectName("SadButton")
        self.MadButton = QtWidgets.QPushButton(Form)
        self.MadButton.setGeometry(QtCore.QRect(170, 80, 75, 23))
        self.MadButton.click.connect(self.MadButton)
        self.MadButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.MadButton.setObjectName("MadButton")
        self.DepressedButton = QtWidgets.QPushButton(Form)
        self.DepressedButton.setGeometry(QtCore.QRect(240, 80, 75, 23))
        self.DepressedButton.clicked.connect(self.DepressedButton)
        self.DepressedButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.DepressedButton.setObjectName("DepressedButton")
        self.TiredButton = QtWidgets.QPushButton(Form)
        self.TiredButton.setGeometry(QtCore.QRect(310, 80, 75, 23))
        self.TiredButton.click.connect(self.TiredButton)
        self.TiredButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.TiredButton.setObjectName("TiredButton")
        self.ChallengingButton = QtWidgets.QPushButton(Form)
        self.ChallengingButton.setGeometry(QtCore.QRect(380, 80, 75, 23))
        self.ChallengingButton.click.connect(self.ChallengingButton)
        self.ChallengingButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.ChallengingButton.setObjectName("ChallengingButton")
        self.OtherButton = QtWidgets.QPushButton(Form)
        self.OtherButton.setGeometry(QtCore.QRect(450, 80, 75, 23))
        self.OtherButton.click.connect(self.OtherButton)
        self.OtherButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.OtherButton.setObjectName("OtherButton")
        self.WorkButton = QtWidgets.QPushButton(Form)
        self.WorkButton.setGeometry(QtCore.QRect(30, 180, 75, 23))
        self.WorkButton.click.connect(self.WorkButton)
        self.WorkButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.WorkButton.setObjectName("WorkButton")
        self.SchoolButton = QtWidgets.QPushButton(Form)
        self.SchoolButton.setGeometry(QtCore.QRect(100, 180, 75, 23))
        self.SchoolButton.click.connect(self.SchoolButton)
        self.SchoolButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.SchoolButton.setObjectName("SchoolButton")
        self.ParentsButton = QtWidgets.QPushButton(Form)
        self.ParentsButton.setGeometry(QtCore.QRect(170, 180, 75, 23))
        self.ParentsButton.click.connect(self.ParentsButton)
        self.ParentsButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.ParentsButton.setObjectName("ParentsButton")
        self.FriendsButton = QtWidgets.QPushButton(Form)
        self.FriendsButton.setGeometry(QtCore.QRect(240, 180, 75, 23))
        self.FriendssButton.click.connect(self.FriendsButton)
        self.FriendsButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.FriendsButton.setObjectName("FriendsButton")
        self.ResponsibilitiesButton = QtWidgets.QPushButton(Form)
        self.ResponsibilitiesButton.setGeometry(QtCore.QRect(310, 180, 101, 23))
        self.ResponsibilitiesButton.click.connect(self.ResponsibilitiesButton)
        self.ResponsibilitiesButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.ResponsibilitiesButton.setObjectName("ResponsibilitiesButton")
        self.SoButton = QtWidgets.QPushButton(Form)
        self.SoButton.setGeometry(QtCore.QRect(400, 180, 75, 23))
        self.SoButton.click.connect(self.SoButton)
        self.SoButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.SoButton.setObjectName("SoButton")
        self.OtherButton2 = QtWidgets.QPushButton(Form)
        self.OtherButton2.setGeometry(QtCore.QRect(470, 180, 75, 23))
        self.OtherButton2.click.connect(self.OtherButton2)
        self.OtherButton2.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(58, 134, 255);\n"
"    color: rgb(65, 65, 65);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 255, 103);\n"
"    color: rgb(65, 65, 65);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(78, 134, 255);\n"
"    \n"
"}")
        self.OtherButton2.setObjectName("OtherButton2")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(190, 130, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(160, 40, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 250, 511, 131))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setGeometry(QtCore.QRect(220, 220, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.BackButton = QtWidgets.QPushButton(Form)
        self.BackButton.setGeometry(QtCore.QRect(30, 420, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.BackButton.setFont(font)
        self.BackButton.click.connect(self.BackButton)
        self.BackButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(20, 0, 0);\n"
"    \n"
"}")
        self.BackButton.setObjectName("BackButton")
        self.DoneButton = QtWidgets.QPushButton(Form)
        self.DoneButton.setGeometry(QtCore.QRect(470, 420, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.DoneButton.setFont(font)
        self.DoneButton.click.connect(self.DoneButton)
        self.DoneButton.setStyleSheet("QPushButton{\n"
"    border-radius: 8pt;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(120, 120, 120);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(20, 0, 0);\n"
"    \n"
"}")
        self.DoneButton.setObjectName("DoneButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def setMood(self, Mood):
        self.currentMood = Mood


    def setReason(self, Reason):
        self.currentReason = Reason

    def addSummaryToDatabase(self, eofsForm):
        Notes = self.plainTextEdit.toPlainText()
        Date = datetime.today().strftime("%m/%d/%Y")
        Time = datetime.today().strftime("%H:%M %p")    # changed format since I gave Ben the wrong time format -agthomas95
        EofsControllerClass.input_eofs(Date, Time, self.currentMood, self.currentReason, Notes)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.HappyButton.setText(_translate("Form", "Happy"))
        self.SadButton.setText(_translate("Form", "Sad"))
        self.MadButton.setText(_translate("Form", "Mad"))
        self.DepressedButton.setText(_translate("Form", "Depressed"))
        self.TiredButton.setText(_translate("Form", "Tired"))
        self.ChallengingButton.setText(_translate("Form", "Challenging"))
        self.OtherButton.setText(_translate("Form", "Other"))
        self.WorkButton.setText(_translate("Form", "Work"))
        self.SchoolButton.setText(_translate("Form", "School"))
        self.ParentsButton.setText(_translate("Form", "Parents"))
        self.FriendsButton.setText(_translate("Form", "Friends"))
        self.ResponsibilitiesButton.setText(_translate("Form", "Responsibilities"))
        self.SoButton.setText(_translate("Form", "S/O"))
        self.OtherButton2.setText(_translate("Form", "Other"))
        self.label2.setText(_translate("Form", "What might be the cause?"))
        self.label1.setText(_translate("Form", "How was your overall mood today?"))
        self.label3.setText(_translate("Form", "Care to elaborate?"))
        self.BackButton.setText(_translate("Form", "Back"))
        self.DoneButton.setText(_translate("Form", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
