# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddNewMeal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#4/23/21:   changed object names to be in line with other files
#           changed window name to "Meal Window"
#           added function to call add_the_meal function when button is pressed
#           -agthomas95

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QCalendarWidget

from MealControllerClass import *

class Ui_MealWindow(object):
    def MealWindowSetup(self, MealForm):
        MealForm.setObjectName("Form")
        MealForm.resize(560, 720)
        MealForm.setMinimumSize(QtCore.QSize(400, 0))
        MealForm.setMouseTracking(True)
        self.FormTitle = QtWidgets.QLabel(MealForm)
        self.FormTitle.setGeometry(QtCore.QRect(130, -20, 301, 139))
        self.FormTitle.setMouseTracking(True)
        self.FormTitle.setLineWidth(1)
        self.FormTitle.setObjectName("FormTitle")
        self.MealTempDate = QtWidgets.QPushButton(MealForm)
        self.MealTempDate.setGeometry(QtCore.QRect(180, 120, 261, 20))
        self.MealTempDate.setObjectName("MealDateLbl")
        self.MealTempDate.clicked.connect(self.showCalendar)
        self.MealTempTime = QtWidgets.QLineEdit(MealForm)
        self.MealTempTime.setGeometry(QtCore.QRect(180, 160, 261, 20))
        self.MealTempTime.setObjectName("MealTimeLbl")
        self.MealTempName = QtWidgets.QLineEdit(MealForm)
        self.MealTempName.setGeometry(QtCore.QRect(180, 200, 261, 20))
        self.MealTempName.setObjectName("MealNameLbl")
        self.MealTempCal = QtWidgets.QLineEdit(MealForm)
        self.MealTempCal.setGeometry(QtCore.QRect(180, 240, 261, 20))
        self.MealTempCal.setObjectName("MealCalLbl")
        self.MealTempFat = QtWidgets.QLineEdit(MealForm)
        self.MealTempFat.setGeometry(QtCore.QRect(180, 280, 261, 20))
        self.MealTempFat.setObjectName("MealFatLbl")
        self.MealTempSug = QtWidgets.QLineEdit(MealForm)
        self.MealTempSug.setGeometry(QtCore.QRect(180, 320, 261, 20))
        self.MealTempSug.setObjectName("MealSugLbl")
        self.MealTempChol = QtWidgets.QLineEdit(MealForm)
        self.MealTempChol.setGeometry(QtCore.QRect(180, 360, 261, 20))
        self.MealTempChol.setObjectName("MealCholLbl")
        self.MealTempSod = QtWidgets.QLineEdit(MealForm)
        self.MealTempSod.setGeometry(QtCore.QRect(180, 400, 261, 20))
        self.MealTempSod.setObjectName("MealSodLbl")
        self.MealTempProt = QtWidgets.QLineEdit(MealForm)
        self.MealTempProt.setGeometry(QtCore.QRect(180, 440, 261, 20))
        self.MealTempProt.setObjectName("MealProtLbl")
        self.MealNotes = QtWidgets.QTextEdit(MealForm)
        self.MealNotes.setGeometry(QtCore.QRect(180, 480, 261, 71))
        self.MealNotes.setObjectName("MealNotesLbl")
        self.FormDate = QtWidgets.QLabel(MealForm)
        self.FormDate.setGeometry(QtCore.QRect(90, 120, 51, 16))
        #ignore form___, it's the text on the ui to the left of the text boxes
        self.FormDate.setObjectName("FormDate")
        self.FormTime = QtWidgets.QLabel(MealForm)
        self.FormTime.setGeometry(QtCore.QRect(90, 160, 51, 16))
        self.FormTime.setObjectName("FormTime")
        self.FormName = QtWidgets.QLabel(MealForm)
        self.FormName.setGeometry(QtCore.QRect(90, 200, 51, 16))
        self.FormName.setObjectName("FormName")
        self.FormCalories = QtWidgets.QLabel(MealForm)
        self.FormCalories.setGeometry(QtCore.QRect(90, 240, 81, 16))
        self.FormCalories.setObjectName("FormCalories")
        self.FormFats = QtWidgets.QLabel(MealForm)
        self.FormFats.setGeometry(QtCore.QRect(90, 280, 81, 16))
        self.FormFats.setObjectName("FormFats")
        self.FormSugars = QtWidgets.QLabel(MealForm)
        self.FormSugars.setGeometry(QtCore.QRect(90, 320, 81, 21))
        self.FormSugars.setObjectName("FormSugars")
        self.FormCholesterol = QtWidgets.QLabel(MealForm)
        self.FormCholesterol.setGeometry(QtCore.QRect(90, 360, 81, 21))
        self.FormCholesterol.setObjectName("FormCholesterol")
        self.FormSodium = QtWidgets.QLabel(MealForm)
        self.FormSodium.setGeometry(QtCore.QRect(90, 400, 81, 21))
        self.FormSodium.setObjectName("FormSodium")
        self.FormProtein = QtWidgets.QLabel(MealForm)
        self.FormProtein.setGeometry(QtCore.QRect(90, 440, 81, 21))
        self.FormProtein.setObjectName("FormProtein")
        self.FormNotes = QtWidgets.QLabel(MealForm)
        self.FormNotes.setGeometry(QtCore.QRect(90, 480, 81, 21))
        self.FormNotes.setObjectName("FormNotes")
        self.PushFinishButton = QtWidgets.QPushButton(MealForm)
        self.PushFinishButton.setGeometry(QtCore.QRect(210, 600, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PushFinishButton.setFont(font)
        self.PushFinishButton.setMouseTracking(False)
        self.PushFinishButton.setCheckable(False)
        self.PushFinishButton.setObjectName("PushFinishButton")
        self.PushFinishButton.clicked.connect(self.button_click)

        self.retranslateUi(MealForm)
        QtCore.QMetaObject.connectSlotsByName(MealForm)

    def button_click(self):
        Name = self.MealTempName.text() 
        Date = self.MealTempDate.text()
        Cal = self.MealTempCal.text()
        Fat = self.MealTempFat.text()
        Sug = self.MealTempSug.text()
        Chol = self.MealTempChol.text()
        Sod = self.MealTempSod.text()
        Prot = self.MealTempProt.text()
        Time = self.MealTempTime.text()
        Notes = self.MealNotes.toPlainText()

        MealControllerClass.add_the_meal(Name, Date, Cal, Fat, Sug, Chol, Sod, Prot, Time, Notes)
        MealForm.close()

    def showCalendar(self):
        self.calendar = QCalendarWidget()
        self.calendar.setGeometry(QtGui.QCursor.pos().x(), QtGui.QCursor.pos().y(), 300, 200)
        self.calendar.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.calendar.setMaximumDate(QtCore.QDate(3000, 1, 1))
        self.calendar.setGridVisible(True)
        self.calendar.clicked.connect(self.getDate)
        self.calendar.show()

    def getDate(self, *args):
        date = self.calendar.selectedDate().toString()
        _translate = QtCore.QCoreApplication.translate
        self.MealTempDate.setText(_translate("MealForm", date))
        self.calendar.close()

    def retranslateUi(self, MealForm):
        _translate = QtCore.QCoreApplication.translate
        MealForm.setWindowTitle(_translate("MealForm", "Meal Window"))
        self.FormTitle.setText(_translate("MealForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">New meal</span></p></body></html>"))
        self.FormDate.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Date</span></p></body></html>"))
        self.FormTime.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Time</span></p></body></html>"))
        self.FormName.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Name</span></p></body></html>"))
        self.FormCalories.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Calories</span></p></body></html>"))
        self.FormFats.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Fats</span></p></body></html>"))
        self.FormSugars.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Sugars</span></p></body></html>"))
        self.FormCholesterol.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Cholesterol</span></p></body></html>"))
        self.FormSodium.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Sodium</span></p></body></html>"))
        self.FormProtein.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Protein</span></p></body></html>"))
        self.FormNotes.setText(_translate("MealForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Notes</span></p></body></html>"))
        self.MealTempDate.setText(_translate("MealForm", "Click for calendar"))
        self.PushFinishButton.setText(_translate("MealForm", "Add meal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MealForm = QtWidgets.QWidget()
    ui = Ui_MealWindow()
    ui.MealWindowSetup(MealForm)
    MealForm.show()
    sys.exit(app.exec_())
